# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vNZ7JcJyVGAdx_cBeBX5wxGFMooZDJRm
"""

import math as m
import numpy as np
import sys

def printf(format, *args) :
    sys.stdout.write(format % args)

r = 0
k = 0.3*np.pi
con = m.pow(10, -8)
true_value = np.cos(k)

def term(x, n):
    return m.pow(-1, n)*m.pow(x, 2*n)/m.factorial(2*n)

for i in range(100):
    r+= term(k, i)
    print(r)
    if abs(r - true_value) < con:
        print("we need %d terms" % (i+1))
        break

print("\nLeThanhPhuong_ITITWE19025_Lab 1_Ex2")