# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/111BwT48mUL2BJK38g3nRDUPMQGNcDQL_
"""

import math
import numpy
import matplotlib.pyplot as p 

real_value = numpy.exp(-5)

l1 = []
l2 = []

def first_way(x, term):
    result = 0
    prev_result = 0
    e_t = 0
    e_a = 0
    print("Calculation using the first way:")
    print("%s%20s%20s%20s" % ("Iteration", "Approximation", "E_a", "E_t"))
    for n in range(0, term):
        prev_result = result
        result += math.pow(-x, n)/math.factorial(n)
        l1.append(result)
        e_t = ((real_value - result)/real_value)
        e_a = ((result - prev_result) / result)
        print("%9d%20.10f%20.10f%20.10f" % (n, result, e_a, e_t))

def second_way(x,term):
    result = 0
    prev_result = 0
    e_t = 0
    e_a = 0
    print("Calculation using the second way:")
    print("%s%20s%20s%20s" % ("Iteration", "Approximation", "E_a", "E_t"))
    for n in range(0, term):
        prev_result = result
        if result != 0:
            flip_result = 1/result
        else:
            flip_result = 0
        flip_result += (math.pow(x, n)/math.factorial(n))
        result = 1/flip_result
        l2.append(result)
        e_t = ((real_value-result)/real_value)
        e_a = ((result - prev_result) / result)
        print("%9d%20.10f%20.10f%20.10f" % (n, result, e_a, e_t))


first_way(5, 21)
print("\n")
second_way(5, 21)

p.subplot(2, 1, 1)
p.plot(l1)
p.title("First way_LeThanhPhuongNam_Lab1_Ex1")

p.subplot(2, 1, 2)
p.plot(l2)
p.title("Second way_LeThanhPhuongNam_Lab1_Ex1")

p.show()