# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xAjwkZvZxYCXj-KGXBE1PLRNFp7JVef7
"""

import numpy as np
import math as m

def func(t):
    return m.pow(t, 4) * np.exp((-3) * m.pow(t, 2))

print("True value: %.10f" % (func(0.5)))

def first_deri(t):
    return (4*m.pow(t, 3) - m.pow(t, 5)*6)*np.exp((-3)*m.pow(t,2))

def first_Taylor(x, a):
    return (func(a) + first_deri(a)*(x-a))

def e_t(x, a):
    return ((func(x)- first_Taylor(x, a))/func(x))

print("First order Taylor series has value: %.10f" % (first_Taylor(0.5, 1)))

print("True error is: %.10f" % (e_t(0.5, 1)))

print("\nLeThanhPhuong_ITITWE19025_Lab 1_Ex3")